name: CMake on multiple platforms

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2025-vs2026, macos-26]
        cfg: [RelWithDebInfo]
        include:
          - os: windows-2025-vs2026
            platform: windows-10-or-11
            cmake_generator: Visual Studio 18 2026
            arch_flags: /arch:AVX2
            sdl: 3.4.14
            sdl-image: 3.4.4
          - os: ubuntu-24.04
            platform: linux-x86-64-v3-glibc6-2-39-libstdcxx-13-2
            cmake_generator: Ninja Multi-Config
            arch_flags: -march=x86-64-v3
            sdl: 3.2.10
            sdl-image: 3.2.4
          - os: macos-26
            platform: macos-26
            cmake_generator: Xcode
            arch_flags:
            sdl: 3.4.14
            sdl-image: 3.4.4
    steps:
    - uses: actions/checkout@v7
      with:
        persist-credentials: false

    - name: Export some shell-only vars to env
      shell: bash
      run: |
        echo "ImageOS=$ImageOS" >> $GITHUB_ENV
        echo "ImageVersion=$ImageVersion" >> $GITHUB_ENV
        echo "CACHE_DISCRIMINATOR=$ImageOS-$ImageVersion-${{ matrix.cfg }}" >> $GITHUB_ENV

    - name: Setup SDL
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install libsdl3-dev libsdl3-image-dev libsdl3-ttf-dev

    - name: Setup SDL
      if: runner.os != 'Linux'
      id: sdl
      uses: libsdl-org/setup-sdl@main
      with:
        build-type: ${{ matrix.cfg }}
        cmake-arguments: >-
          -DCMAKE_C_FLAGS=${{ matrix.arch_flags }}
          -DSDL_SHARED=ON
          -DSDL_STATIC=OFF
        cmake-generator: ${{ matrix.cmake_generator }}
        discriminator: ${{ env.CACHE_DISCRIMINATOR }}
        install-linux-dependencies: true
        version: ${{ matrix.sdl }}
        version-sdl-image: ${{ matrix.sdl-image }}
        version-sdl-ttf: 3-latest

    - name: Dump env and steps
      env:
        STEPS_JSON: ${{ toJSON(steps) }}
      shell: bash
      run: env

    - name: Configure CMake
      if: runner.os == 'Linux'
      run: >-
        cmake -S . -B ./build -G ${{ matrix.cmake_generator }}
        -DCMAKE_C_FLAGS=${{ matrix.arch_flags }}
        -DCMAKE_CXX_FLAGS=${{ matrix.arch_flags }}

    - name: Configure CMake
      if: runner.os == 'Windows'
      run: >-
        cmake -S . -B ./build -G ${{ matrix.cmake_generator }}
        -DCMAKE_SYSTEM_NAME=Windows
        -DCMAKE_SYSTEM_VERSION="10.0"
        -DCMAKE_C_FLAGS=${{ matrix.arch_flags }}
        -DCMAKE_CXX_FLAGS=${{ matrix.arch_flags }}
        -DCMAKE_PREFIX_PATH=${{ steps.sdl.outputs.prefix }}

    - name: Configure CMake
      if: runner.os == 'macOS'
      run: >-
        cmake -S . -B ./build -G ${{ matrix.cmake_generator }}
        -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO
        -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" 
        -DCMAKE_C_FLAGS=${{ matrix.arch_flags }}
        -DCMAKE_CXX_FLAGS=${{ matrix.arch_flags }}
        -DCMAKE_PREFIX_PATH=${{ steps.sdl.outputs.prefix }}

    - name: Build
      run: cmake --build ./build --config ${{ matrix.cfg }}

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest --build-config ${{ matrix.cfg }}

    - name: Install
      run: cmake --install ./build --config ${{ matrix.cfg }} --prefix ./install/${{ matrix.cfg }}

    - name: Ad-Hoc Codesign
      if: runner.os == 'macOS'
      run: codesign -s - -f "./build/release/llss.app" --deep

    - name: Create DMG
      if: runner.os == 'macOS'
      working-directory: ${{ github.workspace }}/build
      run: hdiutil create -size 2g -srcfolder release -volname llss llss.dmg

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: llss-0.X.Y.Z-${{ matrix.platform }}-sdl${{ matrix.sdl }}-${{ matrix.cfg }}
        path: |
          ./build/${{ matrix.cfg }}
          ./install/${{ matrix.cfg }}
        retention-days: 5
