name: CMake on multiple platforms

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      # Set up a matrix to run the following 3 configurations:
      # 1. <Windows, Release, latest MSVC compiler toolchain on the default runner image, default generator>
      # 2. <Linux, Release, latest GCC compiler toolchain on the default runner image, default generator>
      # 3. <Linux, Release, latest Clang compiler toolchain on the default runner image, default generator>
      #
      # To add more build types (Release, Debug, RelWithDebInfo, etc.) customize the cfg list.
      matrix:
        os: [ubuntu-latest, windows-latest]
        cfg: [RelWithDebInfo]
        include:
          - os: windows-latest
            cmake_generator: Visual Studio 18 2026
            c_compiler: cl
            cxx_compiler: cl
            c_flags: /arch:AVX2
            cxx_flags: /arch:AVX2
          - os: ubuntu-latest
            cmake_generator: Ninja Multi-Config
            c_compiler: gcc
            cxx_compiler: g++
            c_flags: -march=x86-64-v3
            cxx_flags: -march=x86-64-v3

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      working-directory: ${{ github.workspace }}
      run: >
        cmake -B ./build
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }}
        -DCMAKE_C_FLAGS=${{ matrix.c_flags }}
        -DCMAKE_CXX_FLAGS=${{ matrix.cxx_flags }}
        -S .

    - name: Build
      run: cmake --build ./build --config ${{ matrix.cfg }}

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest --build-config ${{ matrix.cfg }}

    - name: Install
      run: cmake --install ./build --config ${{ matrix.cfg }} --prefix ${{ github.workspace }}/install/${{ matrix.cfg }}
